#!/system/bin/sh
# Select minimum frequency when screen off (from 300MHz-2.25GHz)
# Remove the hash in front of the maximum screen frequency you want to select

# echo 300000 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
# echo 422400 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
# echo 883200 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
# echo 1190400 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
# echo 1728000 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
# echo 2265600 > /sys/devices/system/cpu/cpu0/cpufreq/screen_off_max_freq
